### ISSUE TITLE
Delete of single entry isn't working

### ISSUE THREAD

**Issue by ryomiyaichi** [peermusic/player-engine#2]
The delete function to remove a single entry isn't working right now.

**Comment by queicherius** [comment]
The problem with this is that the track only gets removed from the engine, but not from the file system. The file system needs the file handler (which we could get with an index, for example), but for the engine we need the index of the engine internal files. Maybe we should rework the way the engine gets the files. Ideas?

**Comment by ryomiyaichi** [comment]
What about adding track.name as parameter on removeTrack (line 76) of example/index.js? 
The fs.delete() function needs a filename, which we could get by the track.name.

Update: 
Change it to something like this. \'' + track.index + '\' **\+ ', \'' + track.name + '\''**
Actually I don't know what the result of the first part (\'' + track.index + '\') is.

**Comment by queicherius** [comment]
Yeah, that would work. We could just change the delete method of the engine to take a file name as well, then it would be a little cleaner.
